### ISSUE TITLE
Procesar configuracion en config.yml especial para el bundle

### ISSUE THREAD

**Issue by mayeco** [rotvulpix/transbank-symfony2#14]
La buena practica para las configuraciones de un bundle es usar el config.yml especial para el key del bundle.

Te dejo un enlace de explicacion:

http://symfony.com/doc/current/cookbook/bundles/configuration.html

**Comment by rotvulpix** [comment]
La parametrización si o sí va por cuenta del usuario y no almacenable en el bundle, ya que Symfony no cuenta con export de config (like Laravel). Va por cuenta del usuario, ya que la ruta a los CGI de Transbank varía de servidor en servidor.
